# Basic
title: JiZhi Dang
subtitle: A blog for Dang
welcome_message: <a href="https://github.com/saduoduo/saduoduo.github.io" target="_blank">嘻嘻嘻</a>
description: 今天也要加油呀！


url: "http://dangandduo.xyz"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: jizhidang
    github: saduoduo
    mail: 969377443@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
